# Site settings

title:       quornings
email:       jesper.quorning@icloud.com
url:         'https://quornings.github.io'
baseurl:
twitter_username:
github_username:  jquorning

# Build settings
markdown: kramdown
permalink: pretty
